### ISSUE TITLE
Specify astro version compatible per tip

### ISSUE THREAD

**Issue by florian-lefebvre** [astrolicious/astro-tips.dev#22]

**Comment by VoxelMC** [comment]
Perhaps a `<CompatibleWith version="" />` component?

**Comment by florian-lefebvre** [comment]
Yeah sounds good!

**Comment by TheOtterlord** [comment]
We could also look at adding a frontmatter value for the version (making it required), then add an override to show it on the page, and even add a warning if it's targeting an old major (e.g. "This is an Astro 3.0 recipe and may not work well with v4.0 or later")

**Comment by florian-lefebvre** [comment]
That sounds powerful!
