### ISSUE TITLE
☂️ External Resources

### ISSUE THREAD

**Issue by OliverSpeir** [astrolicious/astro-tips.dev#63]
## Goals

1. Indexable / Searchable in some way?
 - Provide keywords or descriptions of the resources
2. Easily updated by community members
 - 1 big `.mdx` maybe ?
3. Easy to find on side bar

## Stretch Goal

1. Searchable on its own?
  - have its own section within search bar aka "search external resources"
3. Indexable by author? 
  - Can see all resources by any one author 
  
  ## ToDos
  
- [x] #78
- [x] #77

**Comment by alexanderniebuhr** [comment]
This is a good idea, we - **_I_** - have some notes on this already, will update this issue later.

**Comment by OliverSpeir** [comment]
@alexanderniebuhr Are we tied to the use of the <Link> I feel it makes it harder to read than just a list of links honestly and it takes up a lot more space

**Comment by florian-lefebvre** [comment]
I agree with you Oliver

**Comment by alexanderniebuhr** [comment]
We don't need to use the `<Link>` card, but we should also not just list them as text. In the feature we will add more meta information to them, like dates, authors, etc. So we need a component, which allows for that design.
