### ISSUE TITLE
Update theme to match astrolicious colors

### ISSUE THREAD

**Issue by alexanderniebuhr** [astrolicious/astro-tips.dev#86]
We need to update the current starlight theme of our Astro Tips project to align with the theme colors used on [Astrolicious](https://next.astrolicious.pages.dev/). This will help maintain a consistent look and feel across our web properties.

### Task
1. Visit the [Astrolicious website](https://next.astrolicious.pages.dev/) and note down the primary and secondary color schemes.
2. Use the [Color Theme Editor on Starlight](https://starlight.astro.build/guides/css-and-tailwind/#color-theme-editor) to adjust our current theme to match the noted colors from Astrolicious.
3. Ensure that the changes are visually and functionally coherent across all components of the Astro Tips project.
4. The icon from Astrolicious can be reused; make sure it integrates well with the new theme.

### Additional Notes
- Please test the changes thoroughly to ensure that there are no visual regressions or functionality issues.
- If you encounter any problems or have questions during the update, feel free to ask for help in the 'tips' channel on our Discord server.

### Acceptance Criteria
- The theme colors of the Astro Tips project match those of the Astrolicious site.
- The integration of the theme and icon looks seamless and professional.
- All functionalities are working as expected without any issues.

This update is crucial for maintaining our brand’s visual identity. Looking forward to seeing the refreshed theme. Thank you!

**Comment by at-the-vr** [comment]
I would like to take this Issue

**Comment by at-the-vr** [comment]
Hey Alex, about this ⬇️ 
> The icon from Astrolicious can be reused; make sure it integrates well with the new theme.

Can you clarify this to me?

**Comment by alexanderniebuhr** [comment]
Sure, we thought using the same icon from the website, and maybe also having the word Astro Tips in a similar font, but those are minor details :)

<img width="238" alt="Screenshot 2024-05-01 at 07 47 40" src="https://github.com/astrolicious/astro-tips.dev/assets/45965090/5ce20bba-196a-4230-813e-721d55a6a4b1">

**Comment by at-the-vr** [comment]
Sounds good, I believe that is covered by [starlight logo config](https://starlight.astro.build/reference/configuration/#logo) : current result - https://imgur.com/a/wxEpk3i Is the a dark logo svg available to handle dark mode case as well ?
